colonnes/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

#définition des URLS et des views pour chaque url
urlpatterns = [
    #Page de login. j'utilise l'authentification inclue dans Django
    path('login/', auth_views.LoginView.as_view(template_name='colonnes/login.html'), name='login'),
    #Page de logout
    path('logout/', auth_views.LogoutView.as_view(template_name='colonnes/logged_out.html'), name='logout'),
    #Menu principal de l'application web
    path('', views.deverouillage, name='deverouillage'),
    #Page permettant d'ajouter une nouvelle situation complète
    path('nouvelle_entree/', views.nouvelle_entree, name='nouvelle_entree'),
    #Page Journal, permet de consulter les colonnes de Beck déjà complétées
    path('journal/', views.journal, name='journal'),
    #Page des statistiques
    path('statistiques/', views.statistiques, name='statistiques'),
    #Page des statistiques sur les émotions du jour/semaine/mois
    path('statistiques/<str:periode>/<str:emotion>/', views.statistiques, name='statistiques'),
    #Page pour les conseils de développement personnel
    path('developpement_personnel/', views.developpement_personnel, name='developpement_personnel'),
    #Page des paramètres de l'application
    path('parametres/', views.parametres, name='parametres'),
    #Showimage
    path('showimage/', views.showimage, name='showimage'),
    #Page d'identification
    path('signup/', views.signup, name='signup'),
    #Page d'envoie de mail
    path('envoiemail/', views.envoiemail, name='envoiemail'),
]

eBeck/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("colonnes/", include("colonnes.urls")),
    path("", include("colonnes.urls")),
]

colonnes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Statistiques(models.Model):

        EMOTIONS_STATS = (
        ('TO','Toutes'),
        ('JO','Joie'),
        ('CO','Colère'),
        ('TR','Tristesse'),
        ('DE','Dégoût'),
        ('PE','Peur'),
        )

        dateDeDebut = models.DateTimeField(auto_now=False)
        dateDeFin = models.DateTimeField(auto_now=False)
        emotion = models.CharField(null=False, max_length=2, default="TO", choices=EMOTIONS_STATS)

        def __str__(self):
            return '%s %s %s' % (self.emotion, self.dateDeDebut, self.dateDeFin)


class Tag(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    nom_tag = models.CharField(max_length=30, blank=False, help_text = "Entrez un Tag")

    def __str__(self):          
        return self.nom_tag

class Emotion(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    statut_emo = models.CharField(max_length=30, blank=False, help_text = "Nom de l'émotion")

    def __str__(self):
        return self.statut_emo


class Colonne(models.Model):

    EMOTIONS = (
    ('JO','Joie'),
    ('CO','Colère'),
    ('TR','Tristesse'),
    ('DE','Dégoût'),
    ('PE','Peur'),
    )

    INTENSITE = (
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
    (6,'6'),
    (7,'7'),
    (8,'8'),
    (9,'9'),
    (10,'10'),
    )

    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    situation = models.TextField(max_length=1000, blank=False, help_text = "Décrivez la Situation")
    pensee_aut = models.TextField(max_length=500, blank=False, help_text = "Pensée automatique")
    pensee_alt = models.TextField(max_length=500, blank=False, help_text = "Pensée alternative")
    date_ajout = models.DateTimeField(auto_now=True, help_text = "Date de l'ajout") #prend la date et l'heure en même temps
    date_event = models.DateTimeField(auto_now=False, help_text = "Date de l'événement")
    tag = models.ManyToManyField(Tag)
    emotion = models.CharField(null=False, max_length=2, default="JO", choices=EMOTIONS)
    intensiteAut = models.IntegerField(default=5, choices=INTENSITE)
    intensiteAlt = models.IntegerField(default=5, choices=INTENSITE)


    def __str__(self):
        return self.situation

class Conseil(models.Model):

    type_conseil = models.CharField(max_length=30, blank=False, help_text = "Type du conseil")
    contenu_conseil = models.CharField(max_length=400, blank=False, help_text = "Contenu du conseil")
    def __str__(self):
        return '%s' % (self.contenu_conseil)


class Lien_Ut_Th(models.Model):
    pati = models.ForeignKey(User, related_name='%(class)s_utilisateur', on_delete=models.CASCADE)
    ther = models.ForeignKey(User, related_name='%(class)s_therapeute', on_delete=models.CASCADE)
    def __str__(self):
        return '%s %s' % (self.pati, self.ther)

colonnes/forms.py
from django import forms
from .models import Colonne, Tag, Emotion, Statistiques, Lien_Ut_Th
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse

class StatistiquesForm(forms.ModelForm):
    class Meta:
        model = Statistiques
        fields = ('dateDeDebut', 'dateDeFin', 'emotion')

#formulaire pour ajouter une pensée
class ColonneForm(forms.ModelForm):

    #comme il hérite de ModeLForm, je dois lui préciser la classe Meta et ...
    #... donc le modèle sur lequel il s'appuie pour faire le formulaire
    class Meta:
        model = Colonne
        fields = ('situation', 'pensee_aut', 'emotion', 'intensiteAut', "pensee_alt", 'intensiteAlt', "date_event",'tag')

#formulaire pour ajouter un tag dans les paramètres
class AjoutTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('nom_tag',)

#formulaire d'envoi de mail
class EnvoieMailForm(forms.Form):

    votre_email = forms.EmailField(max_length=254, required=True)
    objet = forms.CharField(max_length=300, required=True)
    email_therapeute = forms.EmailField(max_length=254, required=True)
    situation = forms.CharField(widget=forms.Textarea)
    pensée_automatique= forms.CharField(widget=forms.Textarea)
    pensée_alternative = forms.CharField(widget=forms.Textarea)
    emotion_ressentie = forms.CharField(max_length=2)
    intensité_automatique = forms.IntegerField()
    intensité_alternative = forms.IntegerField()

#formulaire pour ajouter une émotion
class AjoutEmotionForm(forms.ModelForm):
    class Meta:
        model = Emotion
        fields = ('statut_emo',)

#formulaire pour s'authentifier
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

colonnes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from colonnes.models import Colonne, Tag, Emotion, Statistiques, Lien_Ut_Th, Conseil
from colonnes.forms import ColonneForm, AjoutTagForm, AjoutEmotionForm, StatistiquesForm, EnvoieMailForm
from .forms import SignUpForm
from django.shortcuts import redirect
import matplotlib
from matplotlib import pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg
from io import BytesIO, StringIO
import PIL
from PIL import Image
import pylab
import numpy as np
from datetime import datetime, timedelta
from django.utils import timezone
from django.core.mail import send_mail
from django.core import mail

# Create your views here.

def deverouillage(request):
    return render(request, 'colonnes/deverouillage.html', {})

# view pour ajouter une nouvelle pensée
def nouvelle_entree(request):
    if request.method == "POST":
        formColonne = ColonneForm(request.POST)
        if formColonne.is_valid():
            colonne = formColonne.save(commit = False)
            colonne.utilisateur = request.user
            colonne.save()
            messageEnregistrementColonneValide = "Votre colonne a bien été enregistrée."
            return render(request, 'colonnes/nouvelle_entree.html',  {'messageEnregistrementColonneValide':messageEnregistrementColonneValide, 'formColonne': formColonne})
    else :
        #On ajoute le formulaire de colonne et d'ajout de tag à la vue
        formColonne = ColonneForm()
        return render(request, 'colonnes/nouvelle_entree.html', {'formColonne': formColonne})

def journal(request):
    #On instancie les variables globales:
        #Les dates
    dateDebut = datetime.now()
    dateFin = datetime.now()
        #Si la méthode POST est activée...
    if request.method == "POST":
        #... alors on déclare une variable comme étant le StatistiquesForm associé à cet envoi
        formStatistiques = StatistiquesForm(request.POST)
        #On instancie les colonnes de l'utilisateur connecté
        cols = Colonne.objects.filter(utilisateur=request.user).order_by('date_event')
        #Si le form est valide on déroule !
        if formStatistiques.is_valid():
            stats = formStatistiques.save(commit=False)
            #On sauvegarde dans la BDD, le temps de récupérer les valeurs des champs
            stats.save()
            #On récupère la date de début du formulaire
            dateDebut = stats.dateDeDebut
            #Comme l'heure est initialisée à minuit on récupère la date de fin du formulaire et on lui ajoute un jour
            dateFin = stats.dateDeFin + timedelta(days=1)
            #On récupère la valeur du champ émotion
            emotionStats = stats.emotion
            #On récupère les colonnes ayant une date contenue entre la date de début et la date de fin entrées dans le formulaire
            cols = cols.filter(date_event__range=(dateDebut,dateFin))
            #On sélectionne les colonnes présélectionnées contenant la même émotion que celle du formulaire pour les renvoyer sur la page
            colsCherche = cols.filter(emotion='emotionStats')
            #On supprime directement les valeurs dans la base de données pour ne pas créer de conflits potentiels lors d'une future utilisation
            stats.delete()

            #Si "Toutes" a été choisi dans l'onglet des émotions on envoie cols à la vue. cols qui contient toutes les colonnes entre les dates.
            if emotionStats=="TO":
                return render(request, 'colonnes/journal.html', {'cols':cols, 'formStatistiques':formStatistiques})

            #Sinon on renvoie colsCherche
            else:
                return render(request, 'colonnes/journal.html', {'formStatistiques':formStatistiques, 'colsCherche':colsCherche})
        return render(request, 'colonnes/journal.html', {'formStatistiques':formStatistiques})
    else:
        formStatistiques = StatistiquesForm()
        return render(request, 'colonnes/journal.html', {'formStatistiques':formStatistiques})

def statistiques(request):
        #On instancie les variables globales:
            #Les dates
        dateDebut = datetime.now()
        dateFin = datetime.now()
            #Une variable String à vide
        emotionStats =''
            #Une liste contenant les codes ""émotions", ces codes correspondent respectivement à : Joie, Peur, Tristess, Colère, Dégoût
        listeEmotion = ["JO",'PE',"TR","CO","DE"]
            #Une liste qui contiendra les QuerySets à trier
        listeDonnees = [0, 0, 0, 0, 0]
        #Si on envoie la méthode POST...
        if request.method == "POST":
            #... alors on déclare une variable comme étant le StatistiquesForm associé à cet envoi
            formStatistiques = StatistiquesForm(request.POST)
            #On instancie les colonnes de l'utilisateur connecté
            colPeriode = Colonne.objects.filter(utilisateur=request.user)
            #Si le form est valide on déroule !
            if formStatistiques.is_valid():
                stats = formStatistiques.save(commit=False)
                #On sauvegarde dans la BDD, le temps de récupérer les valeurs des champs
                stats.save()
                #On récupère la date de début du formulaire
                dateDebut = stats.dateDeDebut
                #Comme l'heure est initialisée à minuit on récupère la date de fin du formulaire et on lui ajoute un jour
                dateFin = stats.dateDeFin + timedelta(days=1)
                #On récupère la valeur du champ émotion
                emotionStats = stats.emotion
                #On supprime directement les valeurs dans la base de données pour ne pas créer de conflits potentiels lors d'une future utilisation
                stats.delete()
                #... puis on récupère les colonnes ayant une date contenue entre la date de début et la date de fin entrées dans le formulaire
                colPeriode = Colonne.objects.filter(date_event__range=(dateDebut,dateFin))
                #Si l'utilisateur a choisi l'option 'Toutes' pour le champ 'Émotion' du formulaire nous allons lui afficher les moyennes les intensités respectivement pour chacune des émotions
                if emotionStats == 'TO':
                    #On récupère toutes les queryset des colonnes pour chaque Emotion :
                        #On délcare un compteur qui servira à parcourir la liste
                    i=0
                        #On instancie une nouvelle liste catégorisant les colonnes selon leur attribut emotion
                    for emotions in listeEmotion:
                        listeDonnees[i] = colPeriode.filter(emotion__contains=emotions)
                        i=i+1

                    nbrCO = listeDonnees[3].count()
                    #On instancie une liste pour chaque émotion, chaque liste contient les
                    colJO = listeDonnees[0]
                    listeJO = list(colJO)

                    colPE = listeDonnees[1]
                    listePE = list(colPE)

                    colTR = listeDonnees[2]
                    listeTR = list(colTR)

                    colCO = listeDonnees[3]
                    listeCO = list(colCO)

                    colDE = listeDonnees[4]
                    listeDE = list(colDE)

                    #On instancie également les variables qui nous serviront pour calculer les moyennes des attributs d'intensités automatique et alternative
                    intAutJO = 0
                    intAltJO = 0

                    intAutPE = 0
                    intAltPE = 0

                    intAutTR = 0
                    intAltTR = 0

                    intAutCO = 0
                    intAltCO = 0

                    intAutDE = 0
                    intAltDE = 0


                    #Pour chaque liste et donc chaque émotion on fait la somme des attributs d'intensité automatique et alternative
                    i=0
                    for elt in listeJO:
                        intAutJO = intAutJO + listeJO[i].intensiteAut
                        intAltJO = intAltJO + listeJO[i].intensiteAlt
                        i = i +1

                    i=0
                    for elt in listePE:
                        intAutPE = intAutPE + listePE[i].intensiteAut
                        intAltPE = intAltPE + listePE[i].intensiteAlt
                        i = i +1

                    i=0
                    for elt in listeTR:
                        intAutTR = intAutTR + listeTR[i].intensiteAut
                        intAltTR = intAltTR + listeTR[i].intensiteAlt
                        i = i +1

                    i=0
                    for elt in listeCO:
                        intAutCO = intAutCO + listeCO[i].intensiteAut
                        intAltCO = intAltCO + listeCO[i].intensiteAlt
                        i = i +1

                    i=0
                    for elt in listeDE:
                        intAutDE = intAutDE + listeDE[i].intensiteAut
                        intAltDE = intAltDE + listeDE[i].intensiteAlt
                        i = i +1

                    #On instancie les variables des moyennes de l'intensité Automatique et Alternative pour les récupérer plus tard
                    moyIntAutJO = 0
                    moyIntAltJO = 0
                    #On compte le nombre d'éléments dans la liste pour calculer la moyenne
                    compteurJO = len(listeJO)
                    #Pour chaque émotion on calcule les moyennes de l'intensite Automatique et Alternative si l'intensite !=0, c'est à dire s'il existe au moins une colonne avec une telle émotion
                    if compteurJO > 0:
                        moyIntAutJO = intAutJO / compteurJO
                        moyIntAltJO = intAltJO / compteurJO

                    moyIntAutPE = 0

colonnes/templates/colonnes/colonnecomplete.html
{% extends 'colonnes/base.html' %}

<div>

{% block content %}
    {% if user.is_authenticated %}
      <h1 id="centrertitre" class="titre">Votre Journal</h1>
  <div id="content">
    <p id="soustitre" id="centrer">Rechercher dans le Journal</p>
      <p><form method="POST">{% csrf_token %}
      <p id="texte"><label for="id_dateDeDebut">Date de début :</label> <input type="text" name="dateDeDebut" required id="id_dateDeDebut" /></p>
      <p id="texte"><label for="id_dateDeFin">Date de fin :</label> <input type="text" name="dateDeFin" required id="id_dateDeFin" /></p>
      <p>Dates au format JJ/MM/AAAA</p>
      <p id="texte"><label for="id_emotion">Emotion:</label> <select name="emotion" id="id_emotion">
        <option value="TO" selected>Toutes</option>

        <option value="JO">Joie</option>

        <option value="CO">Colère</option>

        <option value="TR">Tristesse</option>

        <option value="DE">Dégoût</option>

        <option value="PE">Peur</option>

  </select></p>
      <button type="submit" id="centrerstats" class="btn btn-primary">Valider</button>
    </form></p>
  </div>

    {% for c in colsCherche %}
    <div id="content">
    <p id="situation">{{c.situation}}</p>
    <p id ="pensee_aut">{{c.pensee_aut}}</p>
    <p><span id="emotion">{{c.emotion}}</span><span id="date">{{c.date_event}}</span></p>
    </div>
    {% endfor %}

    {% for col in cols %}
    <div id="content">
    <p id="situation">{{col.situation}}</p>
    <p id ="pensee_aut">{{col.pensee_aut}}</p>
    <p><span id="emotion">{{col.emotion}}</span><span id="date">{{col.date_event}}</span></p>
    </div>
    {% endfor %}

    {% else %}
    <p>Connectez-vous pour voir votre journal.</p>
    <a href="{% url 'login' %}">Se connecter</a>
    {% endif %}

{% endblock %}

colonnes/templates/colonnes/journal.html
{% extends 'colonnes/base.html' %}

<div>

{% block content %}
    {% if user.is_authenticated %}
      <h1 id="centrertitre" class="titre">Votre Journal</h1>
  <div id="content">
    <p id="soustitre" id="centrer">Rechercher dans le Journal</p>
      <p><form method="POST">{% csrf_token %}
      <p id="texte"><label for="id_dateDeDebut">Date de début :</label> <input type="text" name="dateDeDebut" required id="id_dateDeDebut" /></p>
      <p id="texte"><label for="id_dateDeFin">Date de fin :</label> <input type="text" name="dateDeFin" required id="id_dateDeFin" /></p>
      <p>Dates au format JJ/MM/AAAA</p>
      <p id="texte"><label for="id_emotion">Emotion:</label> <select name="emotion" id="id_emotion">
        <option value="TO" selected>Toutes</option>

        <option value="JO">Joie</option>

        <option value="CO">Colère</option>

        <option value="TR">Tristesse</option>

        <option value="DE">Dégoût</option>

        <option value="PE">Peur</option>

  </select></p>
      <button type="submit" id="centrerstats" class="btn btn-primary">Valider</button>
    </form></p>
  </div>

    {% for c in colsCherche %}
    <div id="content">
    <p id="situation">{{c.situation}}</p>
    <p id ="pensee_aut">{{c.pensee_aut}}</p>
    <p><span id="emotion">{{c.emotion}}</span><span id="date">{{c.date_event}}</span></p>
    </div>
    {% endfor %}

    {% for col in cols %}
    <div id="content">
    <p id="situation">{{col.situation}}</p>
    <p id ="pensee_aut">{{col.pensee_aut}}</p>
    <p><span id="emotion">{{col.emotion}}</span><span id="date">{{col.date_event}}</span></p>
    </div>
    {% endfor %}

    {% else %}
    <p>Connectez-vous pour voir votre journal.</p>
    <a href="{% url 'login' %}">Se connecter</a>
    {% endif %}

{% endblock %}

colonnes/templates/colonnes/logged_out.html
{% extends 'colonnes/base.html' %}

<div>

{% block title %}A bientôt !{% endblock %}

{% block content %}
<div id="content">
  <h2>Deconnexion</h2>
  <p> Vous êtes déconnecté avec succès ! </p>
  <p><a href="{% url 'login' %}">Se connecter</a> de nouveau</p>
</div>
{% endblock %}

</div>

colonnes/templates/colonnes/nouvelle_entree.html
{% extends 'colonnes/base.html' %}

{% block content %}
<h1 id="centrertitre" class="titre">Colonnes de Beck</h1>
<div id="content">
  <p> {{messageEnregistrementColonneValide}}</p>
  <p><form method="POST">{% csrf_token %}
  <p id ="soustitre">Ajouter Nouvelles Colonnes</p>
  <p id="textecolonne"><label for="id_situation">Description de la situation :</label> <textarea name="situation" cols="40" rows="10" maxlength="1000" required id="id_situation">
  </textarea></p>
  <p id="textecolonne"><label for="id_pensee_aut">Pensées automatiques :</label> <textarea name="pensee_aut" cols="40" rows="10" maxlength="500" required id="id_pensee_aut">
  </textarea></p>
  <p id="textecolonne"><label for="id_emotion">Veuillez choisir l'émotion principale ressentie durant la situation :</label> </br> <select name="emotion" id="id_emotion">
    <option value="JO" selected>Joie</option>

    <option value="CO">Colère</option>

    <option value="TR">Tristesse</option>

    <option value="DE">Dégoût</option>

    <option value="PE">Peur</option>

  </select></p>
  <p id="textecolonne"><label for="id_intensiteAut">Veuillez noter l'intensité de l'émotion ressentie suite à ces pensées automatiques sur l'échelle de 10 :</label> </br> <select name="intensiteAut" id="id_intensiteAut">
    <option value="1">1</option>

    <option value="2">2</option>

    <option value="3">3</option>

    <option value="4">4</option>

    <option value="5" selected>5</option>

    <option value="6">6</option>

    <option value="7">7</option>

    <option value="8">8</option>

    <option value="9">9</option>

    <option value="10">10</option>

  </select></p>
  <p id="textecolonne"><label for="id_pensee_alt">Pensées alternatives :</label> <textarea name="pensee_alt" cols="40" rows="10" maxlength="500" required id="id_pensee_alt">
  </textarea></p>
  <p id="textecolonne"><label for="id_intensiteAlt">Veuillez noter l'intensité de l'émotion ressentie suite à ces pensées alternatives sur l'échelle de 10 :</label> </br> <select name="intensiteAlt" id="id_intensiteAlt">
    <option value="1">1</option>

    <option value="2">2</option>

    <option value="3">3</option>

    <option value="4">4</option>

    <option value="5" selected>5</option>

    <option value="6">6</option>

    <option value="7">7</option>

    <option value="8">8</option>

    <option value="9">9</option>

    <option value="10">10</option>

  </select></p>
  <p id="texte"><label for="id_date_event">Date à laquelle la situation s'est produite :</label> <input type="text" name="date_event" required id="id_date_event" /> <span class="helptext">JJ/MM/AAAA</span></p>
  <p id="texte"><label for="id_tag">Tag :</label> <select name="tag" required id="id_tag" multiple="multiple">
    <option value="4">Famille</option>

    <option value="5">Travail</option>

    <option value="18">Amis</option>

    <option value="19">Loisirs</option>

  </select> </p>
    <p id="centrer">
        <button type="submit" class="btn btn-primary">Enregitrer</button>
    </p>
    </form>
  </p>
</div>

{% endblock %}

colonnes/templates/colonnes/parametres.html
{% extends 'colonnes/base.html' %}



{% block content %}
    {% if user.is_authenticated %}
<h1 id="centrertitre" class="titre">Paramètres</h1>

      <div id="content">
        {{messageEnregistrementTagValide}}
        <form method="POST">{% csrf_token %}
          <p  id="titretag"><label for="id_nom_tag">Nouveau Tag</label></p> <p id="centrer"><input type="text" name="nom_tag" maxlength="30" required id="id_nom_tag" /></p>
          <p  id="boutontag"><button type="submit" class="btn btn-primary">Ajouter un Tag</button></p>
        </form>
    </div>
    <div id="content">
    <p id="boutontherapeute">
      <a href="{% url 'envoiemail' %}" ><button class="btn btn-primary"> Envoyer un mail au thérapeute </button></a>
    </p
  </div>
    {% else %}
    <p>Connectez-vous pour voir vos paramètres.</p>
    <a href="{% url 'login' %}">Se connecter</a>
    {% endif %}

{% endblock %}

colonnes/templates/colonnes/signup.html
{% load staticfiles %}

<html>

    <head>
      	<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title id ="titre_page">eBeck</title>
        <link rel="stylesheet" href="{% static 'css/colonnes.css' %}">
    </head>

    <header class="couleur_bg">

      <img id = "logo_ebeck" src="{% static 'images/ebeck.png' %}" alt="E-Beck">
      <div id="titre_authentification">Inscription</div>

    </header>

    <body class="couleur_bg" id="body_authentification">


      <div id="content">
        <form method="POST" class="post-form">{% csrf_token %}
            <!--{{ formSignUp.as_p }}-->
            <p id="texte"><label for="id_username">Pseudonyme :</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username" /> </p><p class="helptext">Seuls les lettres, chiffres, et symbôles @/./+/-/_ sont autorisés.</span></p>
            <p id="texte"><label for="id_first_name">Prénom :</label> <input type="text" name="first_name" maxlength="30" id="id_first_name" /> </p><p class="helptext">Optionnel</p>
            <p id="texte"><label for="id_last_name">Nom :</label> <input type="text" name="last_name" maxlength="30" id="id_last_name" /> </p><p class="helptext">Optionnel</p>
            <p id="texte"><label for="id_email">Email :</label> <input type="email" name="email" maxlength="254" required id="id_email" /></p>
            <p id="texte"><label for="id_password1">Mot de passe :</label> <input type="password" name="password1" required id="id_password1" /> </p>
            <p id="texte"><label for="id_password2">Confirmation mot de passe :</label> <input type="password" name="password2" required id="id_password2" /><span class="helptext"><ul><li>Votre mot de passe ne peut être similaire à d'autres informations personnelles</li><li>Votre mot de passe doit contenir au moins 8 caractères.</li><li>Votre mot de passe ne peut pas contenir que des chiffres.</li></ul></span></p>
        <button type="submit" id="submit_inscription_button" class="btn btn-primary"> S'inscrire </button>
        </form>
      </div>


        <a href="{% url 'login' %}" id="authentifier_inscription"> S'authentifier
        </a>

    </div>

    </body>

</html>

colonnes/templates/colonnes/statistiques.html
{% extends 'colonnes/base.html' %}


{% block content %}
    {% if user.is_authenticated %}
<h1 id="centrertitre" class="titre">Statistiques</h1>
<div id="content">
    <p id="soustitre" id="centrer">Recherche pour statistiques</p>
    <p><form method="POST">{% csrf_token %}
    <p id="texte"><label for="id_dateDeDebut">Date de début :</label> <input type="text" name="dateDeDebut" required id="id_dateDeDebut" /></p>
    <p id="texte"><label for="id_dateDeFin">Date de fin :</label> <input type="text" name="dateDeFin" required id="id_dateDeFin" /></p>
    <p>Dates au format JJ/MM/AAAA</p>
    <p id="texte"><label for="id_emotion">Emotion:</label> <select name="emotion" id="id_emotion">
      <option value="TO" selected>Toutes</option>

      <option value="JO">Joie</option>

      <option value="CO">Colère</option>

      <option value="TR">Tristesse</option>

      <option value="DE">Dégoût</option>

      <option value="PE">Peur</option>

</select></p>
    <button type="submit" id="centrerstats" id="texte" class="btn btn-primary">Valider</button>
  </form></p>
    {% else %}
    <p>Connectez-vous pour voir vos statistiques.</p>
    <a href="{% url 'login' %}">Se connecter</a>
    {% endif %}
{% endblock %}